### ISSUE TITLE
Merging time-series.

### ISSUE THREAD

**Issue by ProgramErgoSum** [tonyskn/node-redis-timeseries#7]
Note an issue; but, a user question.

I will have two sources of data that publish at an arbitrary rate. I would like to merge these time series into a third one by taking a 1 minute slice of the other two time series. How do I do this with node-redis-timeseries ?

**Comment by alph486** [comment]
@ProgramErgoSum - you could also, as part of the block of code where you `recordHit` for series 1 and 2, do `getHits` for the other series and combine the values on the fly then `recordHit` for your 3rd series. This will ensure youve got a third series with the added values. This gets you the data "merged" in the sense that for a given timestamp series3 = series1+series2. This may have been what @risseraka was suggesting.
